# Utiliser la dernière version d'Ubuntu comme image de base
FROM ubuntu:latest

# Mettre à jour APT
RUN apt-get update

# Mettre à niveau les logiciels installés
RUN apt-get upgrade -y

# Définir la commande à exécuter lorsque le conteneur démarre
CMD echo "Hello, World!"